### ISSUE TITLE
Build fails when src folder is missing

### ISSUE THREAD

**Issue by FlorianKirmaier** [gluonhq/gluonfx-maven-plugin#108]
At least that's what happened to me.
I had a project without a src-folder and it only started after adding the src folder with an empty java class.
It's probably related to the following issue: #24

**Comment by jperedadnr** [comment]
The current plugin works for the native image goals without `src` folder (but the javafx-maven plugin fails if `target/classes` is [empty](https://github.com/openjfx/javafx-maven-plugin/blob/master/src/main/java/org/openjfx/JavaFXBaseMojo.java#L191)), providing `target/classes` exists (it can be empty, though this shouldn't be needed at all).

Since this is not a common setup, feel free to reopen the issue or file a new one to the JavaFX Maven plugin issue tracker.
