### ISSUE TITLE
Plugin should not put generated sources in `src` directory

### ISSUE THREAD

**Issue by wimdeblauwe** [gluonhq/gluonfx-maven-plugin#24]
Using the `ios-sim` target with the Maven plugin there are sources generated in `src/ios` (`Default-Info.plist` file and `assets` directory). It would be better if they are put in `target` if they are generated.

**Comment by jperedadnr** [comment]
There is a reason for that: Default-info.plist and Assets folder are resources for iOS, provided as an initial default version, so the developer can modify them (i.e. provide a different iconset). 

These can't be added to target, since on every `clean` they would be removed, the changes would be lost and the project would always use the default resources.

**Comment by johanvos** [comment]
We can probably use something like generated-src for this?

**Comment by wimdeblauwe** [comment]
Maybe there can be a separate Maven goal to put them where they are now as
“example”?

Op di 18 jun. 2019 om 19:00 schreef Johan Vos <notifications@github.com>

**Comment by jperedadnr** [comment]
Plugin already uses `target/gluonfx/$arch-$os/gensrc` for this.
