### ISSUE TITLE
graalvmHome in POM not used by plugin anymore (regression, worked in 0.1.28)

### ISSUE THREAD

**Issue by plotters** [gluonhq/gluonfx-maven-plugin#245]
1. Works fine:
[DEBUG] Configuring mojo 'com.gluonhq:client-maven-plugin:**0.1.28**:build' with basic configurator -->
[DEBUG]   (f) attachList = []
[DEBUG]   (f) basedir = /home/user
[DEBUG]   (f) enableSWRendering = false
[DEBUG]   (f) executable = java
[DEBUG]   (f) graalvmHome = /opt/graalvm/graalvm-ce-java11-20.2.0

2. Does not use `graalvmHome` as defined in POM:
[DEBUG] Configuring mojo 'com.gluonhq:client-maven-plugin:**0.1.31**:build' with basic configurator -->
[DEBUG]   (f) attachList = []
[DEBUG]   (f) basedir = /home/user
[DEBUG]   (f) enableSWRendering = false
[DEBUG]   (f) executable = java
[DEBUG]   (f) graalvmHome = /opt/graalvm/graalvm-ce-java11-20.2.0
[Tue Aug 25 16:15:33 CEST 2020][INFO] We will now compile your code for x86_64-linux-linux. This may take some time.
java.io.IOException: Error: $JAVA_HOME and $GRAALVM_HOME are undefined

Both versions detect the parameter, but only 0.1.28 uses it.

**Comment by plotters** [comment]
See this [commit](https://github.com/gluonhq/client-maven-plugin/commit/a2209330a8f0b254fec72bdf9d27d0441b5a25b0) probably

**Comment by jperedadnr** [comment]
The [commit](https://github.com/gluonhq/client-maven-plugin/commit/a2209330a8f0b254fec72bdf9d27d0441b5a25b0) has to do with user properties in the command line, like `mvn -DX=Y client:build`.

Even if you set `<graalvmHome/>`, the error you are getting is due to not having defined `JAVA_HOME` nor `GRAALVM_HOME` as environment variables, as required by https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/model/ClassPath.java#L135.

The latter could probably derived the `<graalvmHome/>` if not set. 
For now, it is better if you set $JAVA_HOME and/or $GRAALVM_HOME

**Comment by plotters** [comment]
Thanks for the fast reply. Do you know why it worked in `0.1.28` ?

**Comment by jperedadnr** [comment]
Because of this PR: https://github.com/gluonhq/substrate/pull/690

**Comment by jperedadnr** [comment]
Closing as not an issue anymore. Feel free to reopen if needed.
