### ISSUE TITLE
BufferedImage   awt error

### ISSUE THREAD

**Issue by lilili87222** [gluonhq/gluonfx-maven-plugin#420]
code ,build and run ,fail.

`BufferedImage targetBufferedImage = new BufferedImage(width, height, 5);`

**Comment by jperedadnr** [comment]
AWT is not supported by GraalVM, only partially on Linux.

**Comment by lilili87222** [comment]
new version graalvm support. I copy 3 dll next to native image,it works ok.
https://github.com/oracle/graal/issues/4344

**Comment by ctoabidmaqbool** [comment]
@jperedadnr Unfortunatly AWT/SWING is not fully supported on GraalVM but unfortunatly without them, 100rd of Java library becomes un-usable because most of the libraries are depedendent upon AWT.

> AWT is not supported by GraalVM, only partially on Linux.

E.g. 
[icepdf](https://github.com/pcorless/icepdf)
[FXTrayIcon](https://github.com/dustinkredmond/FXTrayIcon)
[OpenPDF](https://github.com/LibrePDF/OpenPDF)
[jasperreports](https://github.com/TIBCOSoftware/jasperreports)
etc...

what about them?
